### ISSUE TITLE
Patch cannot be applied anymore

### ISSUE THREAD

**Issue by simonschaufi** [rectorphp/vendor-patches#1]
I use the typo3-rector repository and ran `composer update` and got the following error:

```
  - Applying patches for symfony/dependency-injection
    https://raw.githubusercontent.com/symplify/vendor-patch-files/main/patches/generic-php-config-loader.patch (0)
    https://raw.githubusercontent.com/rectorphp/vendor-patches/main/patches/symfony-php-config-loader.patch (1)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://raw.githubusercontent.com/rectorphp/vendor-patches/main/patches/symfony-php-config-loader.patch
```

That means that the file https://github.com/rectorphp/vendor-patches/blob/main/patches/symfony-php-config-loader.patch cannot be applied anymore because the source has changed.

**Comment by TomasVotruba** [comment]
The 2nd patch should be no longer used.

This should help:
https://github.com/rectorphp/rector-src/commit/8eac546e111b9d2f4053c722a7552a2eba9e5836
