### ISSUE TITLE
[error] illuminate-container-container-php.patch cannot be used anymore

### ISSUE THREAD

**Issue by dsdeboer** [rectorphp/vendor-patches#6]
Due to [78cbe88cdc7300efd4cf90244abec2e3c42219bb](https://github.com/illuminate/container/commit/78cbe88cdc7300efd4cf90244abec2e3c42219bb) the patch doesn't work anymore. I'll post a fix :)

**Comment by samsonasik** [comment]
Resolved at https://github.com/rectorphp/vendor-patches/pull/7
